apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2021-03-15T06:29:47Z"
  labels:
    app: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: frontend
  managedFields:
  - apiVersion: build.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:openshift.io/generated-by: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
      f:spec:
        f:output:
          f:to:
            .: {}
            f:kind: {}
            f:name: {}
        f:runPolicy: {}
        f:source:
          f:git:
            .: {}
            f:uri: {}
          f:type: {}
        f:strategy:
          f:dockerStrategy:
            .: {}
            f:from:
              .: {}
              f:kind: {}
              f:name: {}
          f:type: {}
    manager: oc
    operation: Update
    time: "2021-03-15T06:29:47Z"
  - apiVersion: build.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:triggers: {}
      f:status:
        f:lastVersion: {}
    manager: openshift-apiserver
    operation: Update
    time: "2021-03-15T06:29:48Z"
  name: frontend
  namespace: meetup
  resourceVersion: "13354739"
  selfLink: /apis/build.openshift.io/v1/namespaces/meetup/buildconfigs/frontend
  uid: b6ddff2c-ac0d-417e-b7c7-124bed1e0fad
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: frontend:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/vamp924/frontend
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: ubi8:8.0
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: l4NZoytFrqP5HYCEl0zR
    type: GitHub
  - generic:
      secret: -mLPHdMtcOWmxaSnonM0
    type: Generic
  - type: ConfigChange
  - imageChange:
      lastTriggeredImageID: registry.access.redhat.com/ubi8@sha256:8275e2ad7f458e329bdc8c0e7543cff1729998fe515a281d49638246de8e39ee
    type: ImageChange
status:
  lastVersion: 1
