apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
  labels:
    app: frontend
  name: frontend
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: frontend:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/vamp924/frontend
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: ubi8:8.0
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: uU9VpIv29awjXcA2nrwv
    type: GitHub
  - generic:
      secret: zANf0iUx2D52-Q2xYmcq
    type: Generic
  - type: ConfigChange
  - imageChange:
    type: ImageChange
