apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
  labels:
    app: database
  name: database
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
    from:
      kind: DockerImage
      name: registry.redhat.io/rhel8/mysql-80
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
