apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/image.dockerRepositoryCheck: "2021-03-15T11:00:21Z"
  creationTimestamp: "2021-03-15T11:00:19Z"
  generation: 2
  labels:
    app: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: backend
  managedFields:
  - apiVersion: image.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:openshift.io/generated-by: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
      f:spec:
        f:tags:
          .: {}
          k:{"name":"latest-java11"}:
            .: {}
            f:annotations:
              .: {}
              f:openshift.io/imported-from: {}
            f:from:
              .: {}
              f:kind: {}
              f:name: {}
            f:generation: {}
            f:importPolicy: {}
            f:name: {}
            f:referencePolicy:
              .: {}
              f:type: {}
    manager: oc
    operation: Update
    time: "2021-03-15T11:00:19Z"
  name: s2i-java
  namespace: meetup
  resourceVersion: "13435362"
  selfLink: /apis/image.openshift.io/v1/namespaces/meetup/imagestreams/s2i-java
  uid: 3c775ad7-6f6d-4401-b8f5-092c2fa3741d
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: fabric8/s2i-java:latest-java11
    from:
      kind: DockerImage
      name: fabric8/s2i-java:latest-java11
    generation: 2
    importPolicy: {}
    name: latest-java11
    referencePolicy:
      type: Source
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/meetup/s2i-java
  publicDockerImageRepository: registry.apps.ocp4.br77.ru/meetup/s2i-java
  tags:
  - items:
    - created: "2021-03-15T11:00:21Z"
      dockerImageReference: fabric8/s2i-java@sha256:86838c136773a1001eb98fc1c4fe84c8fcb3f49b866f06be8ce847c360c31acb
      generation: 2
      image: sha256:86838c136773a1001eb98fc1c4fe84c8fcb3f49b866f06be8ce847c360c31acb
    tag: latest-java11
