apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/image.dockerRepositoryCheck: "2021-03-15T06:29:48Z"
  creationTimestamp: "2021-03-15T06:29:47Z"
  generation: 2
  labels:
    app: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: frontend
  managedFields:
  - apiVersion: image.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:openshift.io/generated-by: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
      f:spec:
        f:tags:
          .: {}
          k:{"name":"8.0"}:
            .: {}
            f:annotations:
              .: {}
              f:openshift.io/imported-from: {}
            f:from:
              .: {}
              f:kind: {}
              f:name: {}
            f:generation: {}
            f:importPolicy: {}
            f:name: {}
            f:referencePolicy:
              .: {}
              f:type: {}
    manager: oc
    operation: Update
    time: "2021-03-15T06:29:47Z"
  name: ubi8
  namespace: meetup
  resourceVersion: "13354733"
  selfLink: /apis/image.openshift.io/v1/namespaces/meetup/imagestreams/ubi8
  uid: 370ee8b8-e1b0-4c11-b2ce-a2fa8147e47f
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: registry.access.redhat.com/ubi8:8.0
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8:8.0
    generation: 2
    importPolicy: {}
    name: "8.0"
    referencePolicy:
      type: Source
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/meetup/ubi8
  publicDockerImageRepository: registry.apps.ocp4.br77.ru/meetup/ubi8
  tags:
  - items:
    - created: "2021-03-15T06:29:48Z"
      dockerImageReference: registry.access.redhat.com/ubi8@sha256:8275e2ad7f458e329bdc8c0e7543cff1729998fe515a281d49638246de8e39ee
      generation: 2
      image: sha256:8275e2ad7f458e329bdc8c0e7543cff1729998fe515a281d49638246de8e39ee
    tag: "8.0"
